version: '2'

services:
  server:
    image: gislibg/tictactoe:${GIT_COMMIT}
    environment:
      - PGHOST=postgres
      - PGPORT=5432
      - NODE_ENV=production
    ports:
      - "80:8080"
      - "8080:3000"
    depends_on:
      - postgres
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"

