version: '2'

services:
  server:
    image: gislibg/tictactoe
    environment:
      - PGHOST=postgres
      - PGPORT=5432
      - PORT=3000
    ports:
      - "8080:8080"
      - "3000:3000"
    depends_on:
      - postgres
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"

